message: helooooooooooooooooooooooooooooo
server:
  port: 8888
app: aggregatorMicroservice
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/SimunovicDario/configrepo