message: helooooooooooooooooooooooooooooo
server:
  port: 8888
app: application
spring:
  cloud:
    config:
      server:
        overrides:
          app:  YAY
        git:
          uri: https://github.com/SimunovicDario/configrepo